@startuml
cloud cloud [
/move
]
storage move-directory-workflow {
usecase usecase [
jetty-message-consumer
]
rectangle rectangle1 [       
log-message-service
]
 rectangle rectangle2 [       
move-file-service
]
 rectangle rectangle3 [       
payload-from-template
]
usecase usecase2 [
jetty-standard-response-producer
] 
}
cloud -> usecase
usecase -> rectangle1
rectangle1 -> rectangle2
rectangle2 -> rectangle3
rectangle3 -> usecase2
usecase2 -> cloud
@enduml