@startuml
cloud cloud [
/unzip
]
storage unzip-file-workflow {
usecase usecase [
jetty-message-consumer
]
rectangle rectangle1 [       
log-message-service
]
 rectangle rectangle2 [       
read-file-service
]
 rectangle rectangle3 [       
unzip-service
]
rectangle rectangle4 [       
move-file-service
]
rectangle rectangle5 [       
payload-from-template
]
usecase usecase2 [
jetty-standard-response-producer
] 
}
cloud -> usecase
usecase -> rectangle1
rectangle1 -> rectangle2
rectangle2 -> rectangle3
rectangle3 -> rectangle4
rectangle4 -> rectangle5
rectangle5 -> usecase2
usecase2 -> cloud
@enduml